server:
  port: 8085

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://postgres:5432/users
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.xml

eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka/

jwt:
  secret: mySecretKey123456789012345678901234567890
  expiration: 86400000 # 24 hours

management:
  endpoints:
    web:
      exposure:
        include: "*"
